### Nomenclatures
### C_mobile_j      mobile H concentration in "j" material, where j = CuCrZr, Cu, W
### C_trapped_j     trapped H concentration in "j" material, where j = CuCrZr, Cu, W
### C_total_j       total H concentration in "j" material, where j = CuCrZr, Cu, W
###
### S_empty_j       empty site concentration in "j" material, where j = CuCrZr, Cu, W
### S_trapped_j     trapped site concentration in "j" material, where j = CuCrZr, Cu, W
### S_total_j       total site H concentration in "j" material, where j = CuCrZr, Cu, W
###
### F_permeation    permeation flux
### F_recombination recombination flux
###
### Sc_             Scaled
### Int_            Integrated
### ScInt_          Scaled and integrated

thickness_monoblock = ${units 6e-3 m}
rings = '1 1 2 12' # '1 30 20 110' # Number of rings in each circle or in the enclosing square of the mesh
num_layer_mesh_thickness = 1

## Mesh generated by ConcentricCircleMeshGenerator and saved as "2DMonoblock.e"
[Mesh]
    [ccmg]
        type = ConcentricCircleMeshGenerator
        num_sectors = 12
        rings = ${rings}
        radii = '${units 6 mm -> m} ${units 7.5 mm -> m} ${units 8.5 mm -> m}'
        has_outer_square = on
        pitch = ${units 28 mm -> m}
        portion = left_half
        preserve_volumes = false
        smoothing_max_it = 3
    []
    [ccmg_extrude]
        type = MeshExtruderGenerator
        input = ccmg
        num_layers = ${num_layer_mesh_thickness}
        extrusion_vector = '0 0 ${thickness_monoblock}'
        bottom_sideset = 'front'
        top_sideset = 'back'
    []
    [ssbsg1]
        type = SideSetsBetweenSubdomainsGenerator
        input = ccmg_extrude
        primary_block = '4'     # W
        paired_block = '3'      # Cu
        new_boundary = '4to3'
    []
    [ssbsg2]
        type = SideSetsBetweenSubdomainsGenerator
        input = ssbsg1
        primary_block = '3'     # Cu
        paired_block = '4'      # W
        new_boundary = '3to4'
    []
    [ssbsg3]
        type = SideSetsBetweenSubdomainsGenerator
        input = ssbsg2
        primary_block = '3'     # Cu
        paired_block = '2'      # CuCrZr
        new_boundary = '3to2'
    []
    [ssbsg4]
        type = SideSetsBetweenSubdomainsGenerator
        input = ssbsg3
        primary_block = '2'     # CuCrZr
        paired_block = '3'      # Cu
        new_boundary = '2to3'
    []
    [ssbsg5]
        type = SideSetsBetweenSubdomainsGenerator
        input = ssbsg4
        primary_block = '2'     # CuCrZr
        paired_block = '1'      # H2O
        new_boundary = '2to1'
    []
    [bdg]
        type = BlockDeletionGenerator
        input = ssbsg5
        block = '1'             # H2O
    []

[]

[ICs]
  [temp]
    type = ConstantIC
    variable = temp
    value = 800
  []
[]

[Problem]
    type = OpenMCCellAverageProblem
    verbose = true
    scaling = 100.0
    temperature_blocks = '2 3 4'    

    cell_level = 0
    max_batches = 100
    batch_interval = 10
    particles = 100000
    source_strength = 2.3e16 # Particles/s.

    
    volume_calculation = vol

    check_tally_sum = false
    [Tallies]
      [heat_source]
        type = MeshTally
        mesh_template = 'neutronics_in.e'
        score = 'heating_local flux'
        # tally_trigger = 'rel_err none'
        # tally_trigger_threshold = '0.05 1.0'
        output = unrelaxed_tally_std_dev
      []
    []
  []

  [UserObjects]
    [vol]
      type = OpenMCVolumeCalculation
      n_samples = 50000
    []
  []

  [Postprocessors]
    [heat_source]
      type = ElementIntegralVariablePostprocessor
      variable = heating_local
    []
    [heat_source_RelativeError]
      type = TallyRelativeError
      tally_score = heating_local
    []
  []

  [Executioner]
    type = Transient
  []

  [Outputs]
    exodus = true
    csv = true
  []
